server.port=8080

spring.application.name=ewm-main-service

# Database
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ewmdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Initialization
spring.sql.init.mode=always

# Stats Service URL
stats-service.url=http://stats-server:9090

# Logging
logging.level.ru.practicum.ewm=DEBUG