-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
    );

-- Таблица категорий
CREATE TABLE IF NOT EXISTS categories (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(50) NOT NULL UNIQUE
    );

-- Таблица локаций
CREATE TABLE IF NOT EXISTS locations (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         lat FLOAT NOT NULL,
                                         lon FLOAT NOT NULL
);

-- Таблица событий
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation TEXT NOT NULL,
    category_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR(20) NOT NULL,
    title VARCHAR(120) NOT NULL,
    views BIGINT DEFAULT 0 NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (initiator_id) REFERENCES users(id),
    FOREIGN KEY (location_id) REFERENCES locations(id)
    );

-- Таблица запросов на участие
CREATE TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        event_id BIGINT NOT NULL,
                                        requester_id BIGINT NOT NULL,
                                        status VARCHAR(20) NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events(id),
    FOREIGN KEY (requester_id) REFERENCES users(id),
    CONSTRAINT uq_request UNIQUE (event_id, requester_id)
    );

-- Таблица подборок
CREATE TABLE IF NOT EXISTS compilations (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            title VARCHAR(50) NOT NULL UNIQUE,
    pinned BOOLEAN NOT NULL
    );

-- Таблица связей подборок и событий
CREATE TABLE IF NOT EXISTS compilation_events (
                                                  compilation_id BIGINT NOT NULL,
                                                  event_id BIGINT NOT NULL,
                                                  PRIMARY KEY (compilation_id, event_id),
    FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
    );

-- Добавляем начальные данные для тестов
INSERT INTO categories (name) VALUES ('Концерты') ON CONFLICT (name) DO NOTHING;
INSERT INTO categories (name) VALUES ('Выставки') ON CONFLICT (name) DO NOTHING;
INSERT INTO categories (name) VALUES ('Спорт') ON CONFLICT (name) DO NOTHING;
INSERT INTO categories (name) VALUES ('Театр') ON CONFLICT (name) DO NOTHING;
INSERT INTO categories (name) VALUES ('Прогулки') ON CONFLICT (name) DO NOTHING;